version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install -g npm
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      - cdk synth -o build
artifacts:
  files:
    - build/*
  discard-paths: yes
