version: 0.2

env:
  variables:
    S3_BUCKET: ""

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install -g npm
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      - cdk synth -o build -c S3_BUCKET=$S3_BUCKET
artifacts:
  files:
    - build/*
  discard-paths: yes